server:
  port: 9000

config:
  path: C:/dev/git/riskwarning.msg/src/main/resources/app.properties

# 定时调度池配置
schedule:
  corePoolSize: 10
  maxPoolSize: 200
  queueCapacity: 10

logging:
  level:
    com.hncy58.bigdata.gateway.mapper: debug

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  session:
    store-type: none
  application:
    name: Bigdata-Gateway
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    mysql:
      name: mysql
      url: jdbc:mysql://localhost:3306/bigdata?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: tokings
      password: 19890625
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
    impala:
      name: impala
      url: jdbc:impala://node01:21050
      username: tokings
      password: 19890625
      # 使用impala数据源
      type: com.cloudera.impala.jdbc41.DataSource
      driver-class-name: com.cloudera.impala.jdbc41.DataSource

mybatis:
  #注意：一定要对应mapper映射xml文件的所在路径
  mapper-locations: classpath:mybatis/*.xml
  # 注意：对应实体类的路径
  type-aliases-package: com.hncy58.riskwarning.msg.model
